### ISSUE TITLE
[feature-request] add domain redirects

### ISSUE THREAD

**Issue by davdenic** [koninklijke-collective/my_redirects#10]
Hi
is it possible to add domains redirect?
thank you
D.

**Comment by bmoex** [comment]
Hi David,

I think this is already possible with domain records. Can you please explain what your goal is?
See:
![screen shot 2016-06-03 at 11 05 35](https://cloud.githubusercontent.com/assets/2414665/15774175/3e4d2f4a-297b-11e6-9e96-c2732c8e8543.png)


Kind regards,

Benjamin Serfhos

**Comment by davdenic** [comment]
Hi Benjamin
Yes your are right but the editor has to setup in different ways and that could drive to poor UX. 
so the goal is to have all kind of redirects in the same module. 
Thanks

**Comment by bmoex** [comment]
I've decided to skip this feature. 
I think this should always be done via your host configuration (apache/nginx). Thanks for your request though.
