### ISSUE TITLE
Redirects to files not possible

### ISSUE THREAD

**Issue by klodeckl** [koninklijke-collective/my_redirects#18]
If a link to a file is made, the link does not work.

And also links to other records e.g. news using the linkhandler extension (https://github.com/cobwebch/linkhandler) do not work.

**Comment by schmitzal** [comment]
Hi,

for the files issue I just changed RedirectService.php Line 180 to:

`        if (MathUtility::canBeInterpretedAsInteger($destination)) {
            $destination = $this->generateLink((int) $destination);
        } else {
			\TYPO3\CMS\Core\Core\Bootstrap::getInstance()->loadCachedTca();
			$TSFE = GeneralUtility::makeInstance('TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController');
			$TSFE->cObj = GeneralUtility::makeInstance('TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer');

			$destination = $TSFE->cObj->typoLink_URL(
				array('parameter' => $destination)
			);
		}`

Maybe just replace the hole link generation with the typolink way? The link handling in extbase is shit...

Best
Alex

**Comment by janviehweger** [comment]
**Link:** 
`/some/path/to/redirect/file.pdf`
**Domain:** 
`www.example.com`
**Target:** 
`file:99`

redirects to: 
www.example.com/file:99

(with the correct status code ;)

any ideas?
best regards
Jan

**Comment by schmitzal** [comment]
With or without my suggested fix?

**Comment by klodeckl** [comment]
It works with your fix. Thanks a lot!

**Comment by bmoex** [comment]
Implemented the fix @schmitzal suggested. Will release when I the new feature will be available.
