### ISSUE TITLE
Redirects with L=1 parameter

### ISSUE THREAD

**Issue by gaumondp** [koninklijke-collective/my_redirects#19]
It looks like we can't do a redirect like this : 

`index.php?id=123&L=1` to page `index.php?id=456&L=1` 

This works but not wanted: `index.php?id=123` to page `index.php?id=456&L=1` 

It looks there is no way to send the L=1 parameter in the **"from link"**.

**Comment by bmoex** [comment]
Hi @gaumondp,

This is probably cause of the `$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashExcludedParameters']` configuration.

You can do the same thing in the TYPO3 backend by creating a page overlay (with the selected language) and redirect to the page in that overlay. 

Is there a specific reason to handle this via the redirects module? :-)


Kind regards,

Benjamin Serfhos

**Comment by gaumondp** [comment]
Sadly since in emergency mode I had to change for another extension... (ods_redirect) that was able to handle the L=1 parameter.

The source of my problem is a site migration where pages URL with` index.php?id=123&L=1 `where sent in emails. We use a 404 extension that broke Apache redirects for such URL so it's why an extension is required.

The 404 ext is pretty nice and worked out-f-the-box : https://typo3.org/extensions/repository/view/error404page

Thanks anyway for trying to help !
