### ISSUE TITLE
Wildcards and regular expressions

### ISSUE THREAD

**Issue by witrin** [koninklijke-collective/my_redirects#20]
> As an editor I would like to have an wildcard character (`*`) or regular expression for the source link, so I can handle large numbers of redirects more effectively.

**Comment by witrin** [comment]
I would like to contribute (pull request) this feature. But I would like to ask first: Would you like to have such a feature too?

**Comment by bmoex** [comment]
Hi @witrin,

It is an interesting user story which would be very nice in the extension. However this is going to be  a challenging on how to make an optimal query to keep it quick and non-conflicting for other redirects (like; which redirect would have priority).

I would love to see your solution, however I am skeptical for backend user interaction (when conflicting redirects occur).

Kind regards,

Benjamin Serfhos 


ps. I will create 2 signals in the \KoninklijkeCollective\MyRedirects\Service\RedirectService::queryByPathAndDomain() so you can at least manipulate it for your own cause. This function returns the redirected redirect :-)

**Comment by bmoex** [comment]
Added 2 signals for \KoninklijkeCollective\MyRedirects\Service\RedirectService::queryByPathAndDomain:
'beforeQueryByPathAndDomain' and 'afterQueryByPathAndDomain'.

See https://github.com/koninklijke-collective/my_redirects/commit/b440c702efc22bebe513a6900d605918c61c3095

**Comment by witrin** [comment]
Hi @bmoex,

thanks for your thoughts about this feature and the signals you've added! I'll try to find a smart solution for the conflict detection, which is a very good point! I thinking about using the automata theory to compare two regular languages but I'm not sure about the complexity if I have to compare the editors input with n other entries.

Kind regards,
Artus

**Comment by witrin** [comment]
[FormalTheory](https://github.com/KendallHopkins/FormalTheory) is such a library for proving two regexes have no overlapping solutions using NFAs; but I should check the complexity and possibly think about caching for this task. But combined with flash messages after saving a redirect in the backend, this could be a proper solution I think. Regarding the priority I could imagine something like:

```sql
SELECT *,
  ROUND(CHAR_LENGTH(url) - CHAR_LENGTH(REPLACE(url, '*', ''))) AS wildcards,
  CHAR_LENGTH(url) AS length
FROM tx_myredirects_domain_model_redirect 
WHERE 'some-url' LIKE REPLACE(url, '*', '%')
ORDER BY wildcards, length DESC;
```

**Comment by witrin** [comment]
@bmoex See #23.

**Comment by fgerards** [comment]
any news on that ?= we relied heavily on the regex_redirect feature of realURL 1.x because we are behind a loadbalancer and cannot do rewriting in the htaccess.

**Comment by fgerards** [comment]
PS: maybe checkout https://github.com/bobosch/ods_redirects/blob/master/class.tx_odsredirects.php , which does regex-based redirects and handles priority

**Comment by mmolle-nelo** [comment]
Are there any news on this?

**Comment by bmoex** [comment]
See #25
