### ISSUE TITLE
Error on installing

### ISSUE THREAD

**Issue by maikusch** [koninklijke-collective/my_redirects#27]
Right after clicking the install button in backend, i get this error:
#1: PHP Warning: file_get_contents(/kunden/homepages/28/d574274134/htdocs/update7/typo3/sysext/core/Resources/Private/Sql/Cache/Backend/Typo3DatabaseBackendCache.sql): failed to open stream: No such file or directory in /homepages/28/d574274134/htdocs/update7/typo3_src-7.6.14/typo3/sysext/core/Classes/Cache/Backend/Typo3DatabaseBackend.php line 441

TYPO3 is 7.6.14

**Comment by bmoex** [comment]
Hi @maikusch, 

If this is all the feedback for installing in the backend I cannot help you out.

When I look at the error it looks more like a caching issue.

Sorry.

Kind regards,

Benjamin Serfhos
