### ISSUE TITLE
Filtering doesn't work over multiple domains

### ISSUE THREAD

**Issue by rtd1978** [koninklijke-collective/my_redirects#31]
First of all, thanks a lot for developing this useful extension.

If you run a multi client TYPO3 system with multiple domains the filtering will not work when choosing "All domains" in redirects overview screen. You have to choose the right domain to get the redirects you looking for.

Thank you.
René

**Comment by bmoex** [comment]
Hi @rtd1978,

I don't know what you mean with "multi client".
My assumption is that you have multiple roots with different domains and you want to view the redirects per different root?

**Comment by rtd1978** [comment]
Hi,

yes, multiple roots with different domains and I'm searching for a "Search term". There will be no results if "All domains" is set in dropdown box.

**Comment by bmoex** [comment]
Hi @rtd1978,

I think this is not an issue but there probably need to be more interaction changes.
The current usecase for the page tree is to find redirects specified to the selected page. Not all redirects with pagetree domains.

I need to remodel the backend module to be more user friendly.

Kind regards,

Benjamin Serfhos

**Comment by rtd1978** [comment]
If there is no usage for "All domains" - just remove it ;-)

**Comment by pkracht** [comment]
@rtd1978 I'm with you. Patched our extension manually. Can we expect this patch going live?
