### ISSUE TITLE
Issue with parameter in the url

### ISSUE THREAD

**Issue by hendrikreimers** [koninklijke-collective/my_redirects#32]
If an redirect URL is called with parameters, for example by Google Adwords, it throws a 404.

Example URL:
http://www.mydomain.com/myredirect/?gclid=2385j3jbns82

Target should be:
http://www.mydomain.com/mypath/to/target/?gclid=2385j3jbns82

but it throws a 404... without the parameter it works fine.

**Comment by bmoex** [comment]
hi @hendrikreimers;

have you tried to define this parameter in `$GLOBALS['TYPO3_CONF_VARS']['FE']['cHashExcludedParameters']`?

The extension make sure to skip these parameters (used for analytics usecases) 
See: 
![screen shot 2017-03-24 at 10 07 42 am](https://cloud.githubusercontent.com/assets/2414665/24287381/c207954c-1079-11e7-96a7-9805130850b9.png)

I hope this solves your issue.

Kind regards,

Benjamin Serfhos
