### ISSUE TITLE
Performance improvment

### ISSUE THREAD

**Issue by lochmueller** [koninklijke-collective/my_redirects#33]
Hey folks,

I have a very fast page and check the code execution. The redirect check need a lot of power in the frontend, only because the objects are build with the ObjectManager. I checked the code, the ObjectManager features are not used at all (DI & initializeObject call). The performance is much faster if the internal objects are build with GeneralUtility::makeInstance only.

![image](https://cloud.githubusercontent.com/assets/3907126/24256801/62448a1a-0fe9-11e7-91ce-6819fe27ea0e.png)

Regards,
Tim

**Comment by bmoex** [comment]
Hi @lochmueller,

I removed the ObjectManager initiation from the RequestController and used sub classes, can you try 3.3.0 and give me feedback if you found new info?

Kind regards,

Benjamin Serfhos

ps. What tool did use to find this process?

**Comment by lochmueller** [comment]
Hey @bmoex 

great patch. But please keep the creation of the SignalSlot-Dispatcher with ObjectManager (or call "initializeObject" manually). The Dispatcher use a initializeObject method.

I checked the cachegrind files of xdebug to find this topic. The output tool is qcachegrind

Regards,
Tim

**Comment by bmoex** [comment]
Thanks Tim!

**Comment by bmoex** [comment]
Just referencing #20 for link :-)
