### ISSUE TITLE
Support MySQL Strict Mode

### ISSUE THREAD

**Issue by codemonkey1988** [koninklijke-collective/my_redirects#38]
When using MySQL Version 5.7 (which is default version in Ubuntu 16.04 LTS), there are MySQL errors when saving a new redirect record.

We get the error, that there is no default value for "last_referrer" column. When we remove the "NOT NULL" for this column, we get the next error, that the value for column domain is invalid. We used "all domains" witch value 0.

Tested on TYPO3 7.6.16, Ubuntu 16.04 and MySQL 5.7

**Comment by bmoex** [comment]
Hi @codemonkey1988,

I have updated the SQL to use the same logic as the core fields in EXT:frontend/ext_tables.sql.
Can you update to 3.3.4 and try again with strict mode?

Kind regards,

Benjamin Serfhos

**Comment by codemonkey1988** [comment]
Hi,

I will update and test it next week. 

Thank you.

**Comment by codemonkey1988** [comment]
I've tested the new version with PHP 7.0.15 and MySQL 5.7.16 and it works.

Thanks.
