### ISSUE TITLE
Editors must not access redirects saved on pid=0

### ISSUE THREAD

**Issue by georgringer** [koninklijke-collective/my_redirects#39]
Redirects on pid=0 must only be accessed by admins. Editors should see a notice if no page is selected.

This would lead to the feature that editors can handle their own redirects

**Comment by glucka** [comment]
From v. 4.0.0 editors cannot create any redirects.
Always this message: No record creation permission for user 3 on page root node 1437745221
On subpages too.

**Comment by georgringer** [comment]
As redirects are part of core in 9, I am closing this issue
