### ISSUE TITLE
my_redirect not working if Ext. pagenotfoundhandling is installed

### ISSUE THREAD

**Issue by runningnet** [koninklijke-collective/my_redirects#46]
Hi,
If we use the Ext. [pagenotfoundhandling](https://typo3.org/extensions/repository/view/pagenotfoundhandling) with your ext. the redirects not working.  I think i found the Problem here [EidUtility.php](https://github.com/koninklijke-collective/my_redirects/blob/master/Classes/Utility/EidUtility.php#L54) 
I think pagenotfoundhandling is hooked into the Page rendering process and if you call  

> $controller->determineId(); 

the pagenotfoundhandling will start and so my_redirect ist not working.
Maybe you have an Idea to fix it ?

Cheers

**Comment by bmoex** [comment]
Hi @runningnet,

Just installed `ext:pagenotfoundhandling` and it seems like its working as intended, so I cannot reproduce your issue.
Can you please share your configuration? 

Kind regards,

Benjamin Serfhos

**Comment by runningnet** [comment]
Hi and sorry for delay,
I try to reproduce this without pagenotfoundhandling. 

If I add a File to the [FE][pageNotFound_handling]  parameter the redirect work anymore.
I use: READFILE:PAth/to/the/file

If I change the value from [FE][pageNotFound_handling] to empty the redirect work very well.

I use Real Url 2.2.1 and Typo3 7.6.18

**Comment by runningnet** [comment]
Hi, 
An update to my tests.
I changed that [Function](https://github.com/koninklijke-collective/my_redirects/blob/master/Classes/Service/RedirectService.php#L308) to that and now it works

`/**
     * @param integer $pageId
     * @return \TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController
     */
    protected function getTypoScriptFrontendController($pageId = 0)
    {
        // Check if GLOBALS['TSFE'] is initiated correctly
        $tmp=$GLOBALS['TYPO3_CONF_VARS']["FE"]["pageNotFound_handling"];
        unset($GLOBALS['TYPO3_CONF_VARS']["FE"]["pageNotFound_handling"]);
        EidUtility::initializeTypoScriptFrontendController($pageId);
        $GLOBALS['TYPO3_CONF_VARS']["FE"]["pageNotFound_handling"]=$tmp;

        return $GLOBALS['TSFE'];
    }`

**Comment by bmoex** [comment]
Hi @runningnet,

I just checked and I can only reproduce this with an invalid page destination. So a redirect that goes to a page that is hidden/deleted.

Can you try the referenced Pull Request locally if this solves your problem too? (https://github.com/koninklijke-collective/my_redirects/pull/47/files)
Thanks in advance!

Kind regards,

Benjamin Serfhos

**Comment by stigfaerch** [comment]
I tried master (6043193), but it did not resolve this problem for me.
But modifications by @runningnet in \KoninklijkeCollective\MyRedirects\Service\RedirectService::getTypoScriptFrontendController
proves to work.
This is on a TYPO3 CMS 8 multisite solution.
@bmoex I hope for this to be opened again - unless this can be solved in some other way?

**Comment by nabossha** [comment]
i encounter the same problem - is there any safe way to fix this?

**Comment by stigfaerch** [comment]
@bmoex Could this issue be reopened?
