### ISSUE TITLE
Possibility of overriding the Template

### ISSUE THREAD

**Issue by robsonrobi** [koninklijke-collective/my_redirects#54]
I really like your extension, would be cool to have the possibility to work with templateRootPaths, etc...

Are you going to develop your extension further ?

**Comment by mbrodala** [comment]
Actually this should just work. Did you make sure to use `module.tx_myredirects` instead of `plugin.tx_myredirects`? See [setup.txt](https://github.com/koninklijke-collective/my_redirects/blob/0b412bcd705b7ca4838d1452a0d25b282a5ed521/Configuration/TypoScript/setup.txt)

**Comment by robsonrobi** [comment]
A spelling mistake :-) 👍 
I xclassed your version and integrated the possibility to make a redirect to a page with a certain language, may be that topic in interesting as a pull request ?

**Comment by mbrodala** [comment]
I'm not the author of this extension. ;-)

Anyways, maybe you want to have a look at #29.
