### ISSUE TITLE
links of extension linkhandler are ignored

### ISSUE THREAD

**Issue by mangopulp** [koninklijke-collective/my_redirects#56]
I use a TYPO3 7.6.23 installation with extension "linkhandler". This extension generates links like this  "record:tx_news_events:tx_news_domain_model_news:1". In KoninklijkeCollective\MyRedirects\Service\RedirectService -> generateLink at Line 278 the if-clause excludes links starting with "record:".

I changed the if-clause from:
```
if (stripos($link, 't3://') === 0 || GeneralUtility::isValidUrl($link) === false)
```
to
```
if (stripos($link, 't3://') === 0 || stripos($link, 'record:') === 0 || GeneralUtility::isValidUrl($link) === false)
```
and then redirects work fine as well for such links of extension "linkhandler".  Could you include this solution into your nice extension?

**Comment by bmoex** [comment]
Hi @mangopulp,

Do you have any link to your extension ```linkhandler```? As I recall, the extension linkhandler is not maintained anymore; while the core has a 'new' feature in TYPO3 8 for link generation using the LinkHandlingInterface (see [Feature 74365](https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.3/Feature-74365-LinkServiceForUnifiedReferencingSyntax.html). 

 I think the best solution is for linkhandler to use the correct internal linking feature; like ```t3://ext_linkhander?name=news&identifier=1```


Hope we can find a good solution.

**Comment by bmoex** [comment]
Hi @mangopulp,

as @mbrodala mentioned #53, linkhandler is implemented in the core; see:
https://docs.typo3.org/typo3cms/extensions/core/8.7/singlehtml/#feature-79626-integrate-record-link-handler

Hope you can refactor for core setup instead of using the extension linkhandler.
