### ISSUE TITLE
Default status code 301

### ISSUE THREAD

**Issue by mindbreaker** [koninklijke-collective/my_redirects#69]
If a new redirect is created, forwarding status code 302 is temporary redirect by default. In most cases you work with a 301 status code. Is it possible to change the preselected status code to 301?

https://support.google.com/webmasters/answer/93633

**Comment by robsonrobi** [comment]
And can you add a expire time for the repsonse header. if a 301 occurs the chrome caches the destination url and you are lost. By adding a customizable expire time we are save 👍 

For example:
$expireTime = 3600;
header('Cache-Control: max-age=' . $expireTime);
header('Expires: '.gmdate('D, d M Y H:i:s', time() + $expireTime).' GMT');

I think those behaviour should be implemented by default for alle redirect reasons...

**Comment by bmoex** [comment]
Hi @robsonrobi,

I do like your idea with the header setup. However, I do not agree with defining this in the extension as possible configuration.
You could already use the ```afterQueryByPathAndDomain``` hook and set the headers based on ```$redirect->getHttpResponse()```.

The original request (defining the default status code) is now configurable via your LocalConfiguration.php. See readme.md.
