### ISSUE TITLE
Editors have no access to redirects

### ISSUE THREAD

**Issue by glucka** [koninklijke-collective/my_redirects#71]
From v. 4.0.0 editors cannot create any redirects.
Always this message: No record creation permission for user 3 on page root node 1437745221
(Editor cannot select a subpage)

**Comment by bmoex** [comment]
Hi @glucka, 

Did you run the upgrade script in the install tool?

Kind regards,

Benjamin Serfhos

**Comment by simare** [comment]
I tried this out on a fresh installation and get the same error.
Any hints?

**Comment by glucka** [comment]
Hi @bmoex , sorry for the late answer. 
It is not possible run the update script. 
Don't see the update action by "Installed Extensions"

**Comment by derpoho** [comment]
@bmoex any updates on this issue?

**Comment by skristofic** [comment]
@bmoex I would need this feature too for my installation, is there an estimated date for its release ?

**Comment by PeterHasitschka** [comment]
@bmoex Can confirm the issue. The Editors of our Typo3 Website can't manage the Redirects. They get the same error as @glucka described.

**Comment by doerler** [comment]
### Solution:

**ignoreRootLevelRestriction** needs to be set in TCA -> https://docs.typo3.org/typo3cms/TCAReference/8.7/Ctrl/Index.html#security

**Comment by glucka** [comment]
I close this issue because this plugin is not necessary in typo3 version 9 and @doerler solution works perfect in version 8. Thanx!
```$GLOBALS['TCA']['tx_myredirects_domain_model_redirect']['ctrl']['security']['ignoreRootLevelRestriction'] = 'true';```

**Comment by PeterHasitschka** [comment]
Thanks @doerler! Works like a charm :-)
