### ISSUE TITLE
Add redirect when change path segement or title

### ISSUE THREAD

**Issue by mhirdes** [koninklijke-collective/my_redirects#8]
Hey, 

first thanks a lot for your work. It would be amazing that if the editor changes the path segement or title of a page so that the URL is not the same as before, a redirect automatically will be created. Often our costumers are confused about, why the page is not reachable by the old URL. 

Maybe a hook after changing the page settings would be a solution. What do you think about that feature?

Kind Regards

**Comment by bmoex** [comment]
Hi Marc,

I don't think this is something for the my_redirects extension. RealURL has a 'expireDays' configuration to make sure the old 'title' is working as before.

In a general `<site>`_page extension I mainly hook the TCEMain with the following data:

```
/**
 * Will issue a backend warning when someone changes a page or news item title and saves.
 * Class Tx_<Site>PagetitleUpdateWarning_TceMain
 */
class TitleUpdateHook
{

    /**
     * Adjustments after database operations. Hook from t3lib/class.t3lib_tcemain.php
     *
     * @param string $status
     * @param string $table
     * @param integer $id
     * @param array $fieldArray
     * @param \TYPO3\CMS\Core\DataHandling\DataHandler $reference
     */
    public function processDatamap_afterDatabaseOperations($status, $table, $id, &$fieldArray, &$reference)
    {
        if ($status == 'update' && $fieldArray['title'] && $table == 'pages') {
            $flashMessage = GeneralUtility::makeInstance(
                'TYPO3\\CMS\\Core\\Messaging\\FlashMessage',
                \TYPO3\CMS\Extbase\Utility\LocalizationUtility::translate($table . '.updatewarning', '<site>_page'),
                'Important!',
                \TYPO3\CMS\Core\Messaging\FlashMessage::ERROR,
                true
            );
            $service = GeneralUtility::makeInstance('TYPO3\\CMS\\Core\\Messaging\\FlashMessageService');
            $queue = $service->getMessageQueueByIdentifier();
            $queue->addMessage($flashMessage);
        } else {
            return;
        }
    }
}
```

In ext_localconf.php
```
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_tcemain.php']['processDatamapClass'][] = 'EXT:' . $_EXTKEY . '/Classes/Hook/TitleUpdateHook.php:Serfhos\\<Site>Page\\Hook\\TitleUpdateHook';
```

I hope this answers your question adequately.

Kind regards,

Benjamin Serfhos

**Comment by mhirdes** [comment]
Hi Benjamin, thanks for your answer. We also tried a workaround, that we fill in the path segment field if it is empty. So if the editor changes the title, the link will not be changed. But I also write to dimitry and he says, the 301 redirect will be implemented in the future. More here: https://github.com/dmitryd/typo3-realurl/issues/164 . That's the best solution at the moment I think. Again, thanks to you.
